<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title">选择影院</h4>
      </div>

      <div class="modal-body cinema-list">
        <div class="input-group">
          <div class="input-group-addon"><label><input type="checkbox" value=""><span>上海</span></label></div>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
        </div>
        <div class="input-group">
          <div class="input-group-addon"><label><input type="checkbox" value=""><span>上海</span></label></div>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
        </div>
        <div class="input-group">
          <div class="input-group-addon"><label><input type="checkbox" value=""><span>上海</span></label></div>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
        </div>
        <div class="input-group">
          <div class="input-group-addon"><label><input type="checkbox" value=""><span>上海</span></label></div>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
          <label><input type="checkbox" value=""><span>上海影城新华路店</span></label>
        </div>

      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-primary">保存</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
      </div>

    </div>
  </div>
</div>