<div class="modal show">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title">选择城市</h4><label class="checkbox-inline"><input type="checkbox" id="chooseCityAll" value="0"> 全选</label>
      </div>

      <div class="modal-body">

        <div class="choosed-city">
          <div class="input-group">
            <div class="input-group-addon">已选</div>
            <span class="label label-default">上海 &times;</span>
            <span class="label label-default">上海 &times;</span>
            <span class="label label-default">上海 &times;</span>
            <span class="label label-default">上海 &times;</span>
            <span class="label label-default">上海 &times;</span>
            <span class="label label-default">上海 &times;</span>
            <span class="label label-default">上海 &times;</span>
            <span class="label label-default">上海 &times;</span>
            <span class="label label-default">上海 &times;</span>
            <span class="label label-default">上海 &times;</span>
            <span class="label label-default">上海 &times;</span>
            <span class="label label-default">上海 &times;</span>
          </div>
        </div>

        <div class="candidate-city">
          <ul class="nav nav-tabs" role="tablist">
            <li class="active"><a href="#section1" aria-controls="section1" role="tab" data-toggle="tab">A B C D E</a></li>
            <li><a href="#section2" aria-controls="section2" role="tab" data-toggle="tab">F G H I J</a></li>
            <li><a href="#section3" aria-controls="section3" role="tab" data-toggle="tab">K L M N P</a></li>
            <li><a href="#section4" aria-controls="section4" role="tab" data-toggle="tab">Q R S T</a></li>
            <li><a href="#section5" aria-controls="section5" role="tab" data-toggle="tab">W S Y Z</a></li>
          </ul>
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="section1">
              <div class="input-group">
                <div class="input-group-addon">A</div>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
              </div>
              <div class="input-group">
                <div class="input-group-addon">B</div>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
              </div>
              <div class="input-group">
                <div class="input-group-addon">C</div>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
              </div>
              <div class="input-group">
                <div class="input-group-addon">D</div>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
                <label><input type="checkbox" value=""><span>上海</span></label>
              </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="section2">...</div>
            <div role="tabpanel" class="tab-pane" id="section3">...</div>
            <div role="tabpanel" class="tab-pane" id="section4">...</div>
            <div role="tabpanel" class="tab-pane" id="section5">...</div>

          </div>
        </div>

      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-primary">保存</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
      </div>

    </div>
  </div>
</div>