<div class="log-area">
  <dl class="log-list">
    <dt>操作记录</dt>
    <dd>2016-03-01 12:00:00 下线 xxxxxxxx</dd>
    <dd>2016-03-01 12:00:00 下线 xxxxxxxx</dd>
    <dd>2016-03-01 12:00:00 下线 xxxxxxxx</dd>
    <dd>2016-03-01 12:00:00 下线 xxxxxxxx</dd>
    <dd>2016-03-01 12:00:00 下线 xxxxxxxx</dd>
    <dd>2016-03-01 12:00:00 下线 xxxxxxxx</dd>
    <dd>2016-03-01 12:00:00 下线 xxxxxxxx</dd>
    <dd>2016-03-01 12:00:00 下线 xxxxxxxx</dd>
    <dd>2016-03-01 12:00:00 下线 xxxxxxxx</dd>
    <dd>2016-03-01 12:00:00 下线 xxxxxxxx</dd>
  </dl>
  <nav>
    <ul class="pager">
      <li><a href="#">上一页</a></li>
      <li>2/10</li>
      <li><a href="#">下一页</a></li>
    </ul>
  </nav>
</div>