<div class="col-sm-3 col-md-2 sidebar">
  <h4>MENU</h4>

  <div class="panel-group" id="menu">

    <div class="panel">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#menu" href="#menu1"><span class="glyphicon glyphicon-send" aria-hidden="true"></span> 合作方管理</a>
      <div id="menu1" class="panel-collapse collapse">
        <div class="list-group">
          <a href="class.html" class="list-group-item">万达票类管理</a>
        </div>
      </div>
    </div>

    <div class="panel">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#menu" href="#menu2"><span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span> 影院管理</a>
      <div id="menu2" class="panel-collapse collapse" role="tabpanel">
        <div class="list-group">
          <a href="cinema.html" class="list-group-item">标准影院库</a>
          <a href="cinema-partner.html" class="list-group-item">合作方影院库</a>
          <a href="cinema-service.html" class="list-group-item">服务类别维护</a>
        </div>
      </div>
    </div>

    <div class="panel">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#menu" href="#menu3"><span class="glyphicon glyphicon-film" aria-hidden="true"></span> 影片管理</a>
      <div id="menu3" class="panel-collapse collapse" role="tabpanel">
        <div class="list-group">
          <a href="movie.html" class="list-group-item">标准影片库</a>
          <a href="movie-partner.html" class="list-group-item">合作方影片库</a>
        </div>
      </div>
    </div>

    <div class="panel">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#menu" href="#menu4"><span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span> 场次及价格管理</a>
      <div id="menu4" class="panel-collapse collapse" role="tabpanel">
        <div class="list-group">
          <a href="showtime.html" class="list-group-item">场次查询</a>
          <a href="charge.html" class="list-group-item">服务费设置</a>
        </div>
      </div>
    </div>

    <div class="panel">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#menu" href="#menu5"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> 活动中心</a>
      <div id="menu5" class="panel-collapse collapse" role="tabpanel">
        <div class="list-group">
          <a href="activity-plan.html" class="list-group-item">活动计划管理</a>
          <a href="activity-unit.html" class="list-group-item">活动单元管理</a>
          <a href="coupon.html" class="list-group-item">优惠券管理</a>
        </div>
      </div>
    </div>

    <div class="panel">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#menu" href="#menu6"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span> 前端配置平台</a>
      <div id="menu6" class="panel-collapse collapse" role="tabpanel">
        <div class="list-group">
          <a href="banner.html" class="list-group-item">前端配置管理</a>
        </div>
      </div>
    </div>

    <div class="panel">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#menu" href="#menu7"><span class="glyphicon glyphicon-file" aria-hidden="true"></span> 订单管理</a>
      <div id="menu7" class="panel-collapse collapse" role="tabpanel">
        <div class="list-group">
          <a href="order-cs.html" class="list-group-item">客服</a>
          <a href="order-op.html" class="list-group-item">运营</a>
        </div>
      </div>
    </div>

    <div class="panel">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#menu" href="#menu8"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> 报表查询</a>
      <div id="menu8" class="panel-collapse collapse" role="tabpanel">
        <div class="list-group">
          <a href="report-finance.html" class="list-group-item">财务报表</a>
          <a href="report-operation.html" class="list-group-item">运营报表</a>
        </div>
      </div>
    </div>

    <div class="panel">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#menu" href="#menu9"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> 评论管理</a>
      <div id="menu9" class="panel-collapse collapse" role="tabpanel">
        <div class="list-group">
          <a href="comment.html" class="list-group-item">评论编辑</a>
          <a href="comment-filtering.html" class="list-group-item">敏感词导入</a>
        </div>
      </div>
    </div>

    <div class="panel">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#menu" href="#menu10"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> 用户权限管理</a>
      <div id="menu10" class="panel-collapse collapse" role="tabpanel">
        <div class="list-group">
          <a href="user.html" class="list-group-item">用户管理</a>
          <a href="authority.html" class="list-group-item">权限管理</a>
          <a href="role.html" class="list-group-item">角色管理</a>
          <a href="ability.html" class="list-group-item">功能管理</a>
        </div>
      </div>
    </div>

  </div>

</div>